using BankingApp.Core.Enums;

namespace BankingApp.Core.Entities;

// represents a single financial movement (income or expense) on a bank account
public class Transaction
{
    public int Id { get; set; }
    public string Description { get; set; } = string.Empty;
    public decimal Amount { get; set; }
    // income or expense — determines how the balance is affected
    public TransactionType Type { get; set; }
    public TransactionCategory Category { get; set; }
    public DateTime Date { get; set; } = DateTime.UtcNow;
    public string? Notes { get; set; }
    // optional external reference e.g. bank transfer id
    public string? ReferenceNumber { get; set; }
    // true when this transaction was created automatically by the recurring payment worker
    public bool IsRecurring { get; set; }
    // snapshot of the account balance immediately after this transaction was applied
    public decimal BalanceAfter { get; set; }
    // foreign key to the account this transaction belongs to
    public int BankAccountId { get; set; }
    public BankAccount BankAccount { get; set; } = null!;
    // nullable — only set when the transaction was generated by a recurring payment
    public int? RecurringPaymentId { get; set; }
    public RecurringPayment? RecurringPayment { get; set; }
    // many-to-many navigation property — one transaction can have multiple tags
    public ICollection<Tag> Tags { get; set; } = new List<Tag>();
}